### ISSUE TITLE
Considering using Chessground

### ISSUE THREAD

**Issue by mobeigi** [Gen1Code/Chess-Lights-Out#1]
Hey @Gen1Code, 

Making an issue here as there is no way to contact you (your Discord link is broken in your profile on Github, might want to update that to a username or email).

I thought you might want to use Chessground (https://github.com/lichess-org/chessground) as your chess board library instead.
I used it recently in a project and found it to be flawless and feature packed (smooth animations, easy to work with, very customisable and has much more support and developers backing it from Lichess).

You should be able to implement the same grid system etc you are applying.

If you want to see an example of general usage, I have a chess project on my Github profile too.

Take care mate.

**Comment by Gen1Code** [comment]
Heya thanks for the suggestion, I dont think I'll be switching as the library bug really only affects dev testing and is otherwise good enough for my use case. 
(Thanks for letting me know about discord link, domain changed 2yrs ago and I didnt notice)
